/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package imposto;

import backEnd.CadCompra;
import backEnd.Produto;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author 55119
 */
public class ComprarProduto extends javax.swing.JFrame {
    private Produto produtos;
    private ArrayList<String> nomeProduto;
    private DefaultTableModel listaProduto;
    private DefaultTableModel compraProduto;
    private ArrayList<Integer> idListaComprar;
    private String idComprar;
    private CadCompra compra;
    private Integer idPessoaLogado;

    /**
     * Creates new form VisualizarProdutos
     */
    public ComprarProduto(Integer idPessoaLogado) {
        initComponents();
        this.produtos = new Produto();
        this.nomeProduto = new ArrayList<>();
        listaProduto = new DefaultTableModel();
        compraProduto = new DefaultTableModel();
        idListaComprar = new ArrayList<>();
        produtos.getProdutos();
        this.idPessoaLogado = idPessoaLogado;

        listarProdutos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        listaProdutos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        comprarProdutos = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        listaProdutos.setBackground(new java.awt.Color(204, 255, 255));
        listaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(listaProdutos);

        jButton1.setText("Adicionar ao carrinho");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Produtos");

        comprarProdutos.setBackground(new java.awt.Color(204, 255, 255));
        comprarProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod de barras", "Preco", "Nome", "Descrição"
            }
        ));
        jScrollPane3.setViewportView(comprarProdutos);

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Comprar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(listaProdutos.getSelectedRow() != -1){
            int i = listaProdutos.getSelectedRow();
            Boolean validatable = true;
            for (Integer id : idListaComprar){
                if(id == produtos.idLista.get(i)){
                    validatable = false;
                }
            }
            
            System.out.println(validatable);
            if(validatable){
                Object[] row = new Object[4];
                comprarProdutos.setModel(compraProduto);
                Object[] colums = {"Cod de Barras", "Preco", "Nome", "Descrição"};
                compraProduto.setColumnIdentifiers(colums);

                idListaComprar.add(produtos.idLista.get(i));
                row[0] = produtos.cod_barrasLista.get(i);
                row[1] = produtos.precoLista.get(i);
                row[2] = produtos.nomeLista.get(i);
                row[3] = produtos.descricaoLista.get(i);
                compraProduto.addRow(row);
            } else{
                JOptionPane.showMessageDialog(this,"Produto ja esta adicionado" , "Erro", 1);
            }
            
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(comprarProdutos.getSelectedRow()!= -1){

            System.out.println(comprarProdutos.getSelectedRow());
            idListaComprar.remove(comprarProdutos.getSelectedRow());
            compraProduto.removeRow(comprarProdutos.getSelectedRow());
            JOptionPane.showMessageDialog(this,"Produto excluido" , "Sucesso", 1);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        idComprar = "";
        for(Integer id : idListaComprar){
            idComprar +=id+";";
        }
        this.compra = new CadCompra(idPessoaLogado,idComprar);
        if(compra.comprar()){
            JOptionPane.showMessageDialog(this, compra.mensagem, "Sucesso", 1 );
            hide();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    public void listarProdutos(){

        Object[] row = new Object[4];
        listaProdutos.setModel(listaProduto);
        Object[] colums = {"Cod de Barras", "Preco", "Nome", "Descrição"};
        listaProduto.setColumnIdentifiers(colums);

        nomeProduto = produtos.nomeLista;
        for (int i = 0; i < nomeProduto.size(); i++) {
            row[0] = produtos.cod_barrasLista.get(i);
            row[1] = produtos.precoLista.get(i);
            row[2] = produtos.nomeLista.get(i);
            row[3] = produtos.descricaoLista.get(i);
            listaProduto.addRow(row);
        }
        
        

    }
    
    public void layoutTable(){
        listaProdutos.setBackground(Color.white);
        listaProdutos.setForeground(Color.black);
        listaProdutos.setGridColor(Color.red);
        listaProdutos.setSelectionForeground(Color.white);
        listaProdutos.setFont(new Font("Tahoma", Font.PLAIN,17));
        listaProdutos.setRowHeight(30);
        listaProdutos.setAutoCreateRowSorter(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable comprarProdutos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable listaProdutos;
    // End of variables declaration//GEN-END:variables
}
